openrewrite/rewrite-quarkus

src/main/resources/META-INF/rewrite/quarkus-upgrade.yml
closes https://github.com/openrewrite/rewrite-quarkus/issues/2
=> quarkus.dev.instrumentation renamed to quarkus.live-reload.instrumentation

src/main/resources/META-INF/rewrite/quarkus-upgrade.yml
Putting a 2.x migration placeholder out there for the benefit of any recipes falling under the 2.x migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0
Once this is in place it'll pave way to put https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0 migrations in place, esp. straightforward recipes like property key migrations
closes https://github.com/openrewrite/rewrite-quarkus/issues/13
=> Quarkus 2.x migration recipes placeholder

build.gradle.kts, src/main/java/org/openrewrite/java/quarkus/quarkus2/GrpcServiceAnnotationToGrpcClient.java, src/main/java/org/openrewrite/java/quarkus/quarkus2/package-info.java, src/main/resources/META-INF/rewrite/quarkus-upgrade.yml, src/test/kotlin/org/openrewrite/java/quarkus/quarkus2/GrpcServiceAnnotationToGrpcClientTest.kt, src/test/kotlin/org/openrewrite/java/quarkus/quarkus2/package-info.java
Quarkus 2.x changes `@io.quarkus.grpc.runtime.annotations.GrpcService` to `@io.quarkus.grpc.GrpcClient`
see: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#grpc
see: https://quarkus.io/guides/grpc-service-consumption
>The io.quarkus.grpc.runtime.annotations.GrpcService annotation was renamed to io.quarkus.grpc.GrpcClient. Furthermore, the @GrpcClient.value() is optional and the service name can be derived from the annotated element.
Please note, this PR puts `quarkus2` recipes into their own package, and there's no reason that it _has_ to be this way. I'm not sure if it's the best thing to do, I just put it there for organizing. Feedback is happily welcome on whether to remove it.
=> Quarkus 2.x changes `@io.quarkus.grpc.runtime.annotations.GrpcService` to `@io.quarkus.grpc.GrpcClient`

src/main/java/org/openrewrite/java/quarkus/MultiTransformHotStreamToMultiHotStream.java, src/main/resources/META-INF/rewrite/quarkus-upgrade.yml, src/test/kotlin/org/openrewrite/java/quarkus/MultiTransformHotStreamToMultiHotStreamTest.kt
Mutiny `multi.transform().hotStream()` to `multi.hotStream()` recipe. Fixes #20
=> Mutiny `multi.transform().hotStream()` to `multi.hotStream()` recipe

src/main/java/org/openrewrite/java/quarkus/ConfigPropertiesToConfigMapping.java, src/main/resources/META-INF/rewrite/quarkus-upgrade.yml, src/test/kotlin/org/openrewrite/java/quarkus/ConfigPropertiesToConfigMappingTest.kt
Convert Quarkus `@ConfigProperties` annotated interfaces to Smallrye `@ConifgMapping`. Fixes #15
=> Convert Quarkus `@ConfigProperties` annotated interfaces to Smallrye `@ConfigMapping` configuration

src/main/java/org/openrewrite/java/quarkus/AddQuarkusMavenPluginGoalVisitor.java, src/main/java/org/openrewrite/java/quarkus/ConfigureQuarkusMavenPluginWithReasonableDefaults.java, src/main/resources/META-INF/rewrite/quarkus-upgrade.yml
Handles the "configuration" part of https://github.com/openrewrite/rewrite-quarkus/issues/6
To be honest, this _should_ be cleaner, but it works, and it's a good glob of "unrefined" code that can be refined to discover better patterns/ergonomics to get things done. tl;dr, good refactoring opportunity.
=> Ability to add goals to the quarkus-maven-plugin + configure reasonable defaults

src/main/resources/META-INF/rewrite/quarkus-upgrade.yml
see: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#avro
closes https://github.com/openrewrite/rewrite-quarkus/issues/16
=> Remove `avro-maven-plugin` as part of Quarkus 2.0 migration

src/main/java/org/openrewrite/java/quarkus/quarkus2/RemoveAvroMavenPlugin.java, src/main/resources/META-INF/rewrite/quarkus-upgrade.yml
closes https://github.com/openrewrite/rewrite-quarkus/issues/30
Changes this recipe so `avro-maven-plugin` will only be removed if the `quarkus-maven-plugin` is also found as a `plugin` within the same `pom.xml`
=> Conditionally remove the `avro-maven-plugin` based on whether the `quarkus-plugin` is found

src/main/resources/META-INF/rewrite/quarkus-upgrade.yml
closes https://github.com/openrewrite/rewrite-quarkus/issues/6
Upgrades quarkus maven plugins for both 1.13.x and placeholder for 2.x in the 2.x upgrade composite.
(do keep in mind, though, that until quarkus maven plugin 2.0.0.Final is released, 2.0.0.CRX is not going to show up.)
=> Upgrade versions of quarkus-maven-plugin

src/test/kotlin/org/openrewrite/java/quarkus/ConfigureQuarkusMavenPluginWithReasonableDefaultsTest.kt, src/test/kotlin/org/openrewrite/java/quarkus/MigrateQuarkusMavenPluginNativeImageGoalTest.kt, src/test/kotlin/org/openrewrite/java/quarkus/quarkus2/RemoveAvroMavenPluginTest.kt
Small thing, but wanted to at least put these in place for future reference.
- retroactively add MigrateQuarkusMavenPluginNativeImageGoalTest for [#26]
- retroactively add RemoveAvroMavenPluginTest for [#31]
- retroactively add ConfigureQuarkusMavenPluginWithReasonableDefaultsTest for [#27]
=> Retroactively add MavenRecipeTests for maven-related recipes

src/main/resources/META-INF/rewrite/category.yml, src/main/resources/META-INF/rewrite/quarkus-upgrade.yml
In order to improve the recipe categorization layout in the UI, move the `Quarkus1to2Migration` recipe to the `quarkus2` package/category.
=> Move quarkus 2.x migration recipe to the quarkus2 category

src/main/resources/META-INF/rewrite/quarkus.yml
in case the quarkus-core bom is used specifically vs. using quarkus-universe-bom (which appears to be used more often)-- but, just using quarkus-bom is done as well 
- https://stackoverflow.com/questions/59880235/how-to-update-the-quarkus-version-used
- https://github.com/quarkusio/quarkus-quickstarts/blob/3c35a1dd3b6a8740d3103ba8a79c2d9ab3caf795/getting-started/pom.xml#L11
- https://groups.google.com/g/quarkus-dev/c/tKGYE5biVt4
=> support bumping quarkus-bom

build.gradle.kts, src/main/java/org/openrewrite/java/quarkus/quarkus2/UsePanacheEntityBaseUniT.java, src/main/resources/META-INF/rewrite/quarkus.yml, src/test/kotlin/org/openrewrite/java/quarkus/quarkus2/UsePanacheEntityBaseUniTTest.kt
Addresses https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#hibernate-reactive-with-panache to keep the original type of Uni<Void> during migration.
=> PanacheEntityBaseUniVoidToUniT to have Uni Voids be replaceable

build.gradle.kts, suppressions.xml
Changes:
- Added tag for CVE-2021-4235 to snake yaml suppression.
- Pinned com.fasterxml.woodstox:woodstox-core to non-vulnerable version.
=> Chore: vulnerability remediation

build.gradle.kts, src/main/resources/META-INF/rewrite/quarkus.yml, src/test/java/org/openrewrite/quarkus/quarkus2/Quarkus1to2MigrationTest.java
- Depend on `rewrite-java-dependencies`
- Add `ChangeParentPom`
- Add tests for dependency upgrades: surface not updated `import` scope dependencies
Fixes #66
For consistency with other projects & predictable placement in release train.
- #66
=> Upgrade Maven parent and Gradle dependencies

src/main/java/org/openrewrite/quarkus/AddQuarkusProperty.java, src/main/java/org/openrewrite/quarkus/QuarkusExecutionContextView.java, src/test/java/org/openrewrite/quarkus/AddQuarkusPropertyTest.java
Add a new recipe to add properties to Quarkus configuration files.
Add properties to configuration files, leveraging profiles.
This recipe was based on `AddSpringProperty` from `rewrite-spring`.
=> Recipe to add properties to Quarkus configuration files

build.gradle.kts, src/main/resources/META-INF/rewrite/category.yml
We don't want any circular dependencies, so if `quarkus-update-recipes` wants to depend on `rewrite-quarkus` it's best to remove the dependency here.
=> Remove quarkus-update-recipes again to allow reuse

src/main/java/org/openrewrite/quarkus/AddQuarkusProperty.java, src/main/java/org/openrewrite/quarkus/ChangeQuarkusPropertyKey.java, src/main/java/org/openrewrite/quarkus/ChangeQuarkusPropertyKeyVisitor.java, src/main/java/org/openrewrite/quarkus/ChangeQuarkusPropertyValue.java, src/main/java/org/openrewrite/quarkus/ChangeQuarkusPropertyValueVisitor.java, src/main/java/org/openrewrite/quarkus/DeleteQuarkusProperty.java, src/main/java/org/openrewrite/quarkus/DeleteQuarkusPropertyVisitor.java, src/main/java/org/openrewrite/quarkus/QuarkusExecutionContextView.java, src/main/java/org/openrewrite/quarkus/QuarkusProfileUtils.java, src/main/java/org/openrewrite/quarkus/search/FindQuarkusProfiles.java, src/main/java/org/openrewrite/quarkus/search/FindQuarkusProperties.java, src/main/java/org/openrewrite/quarkus/search/package-info.java, src/test/java/org/openrewrite/quarkus/AddQuarkusPropertyTest.java, src/test/java/org/openrewrite/quarkus/ChangeQuarkusPropertyKeyTest.java, src/test/java/org/openrewrite/quarkus/ChangeQuarkusPropertyValueTest.java, src/test/java/org/openrewrite/quarkus/DeleteQuarkusPropertyTest.java, src/test/java/org/openrewrite/quarkus/search/FindQuarkusProfilesTest.java, src/test/java/org/openrewrite/quarkus/search/FindQuarkusPropertiesTest.java
Add recipes to find properties and profiles in use, and to change property keys.
Adding recipes to resolve #69.
@gsmet @timtebeek 
~~No workarounds for dealing with Quarkus profiles. Specs for microprofile config shows only a single profile per property, but @gsmet's example has two. Is it allowed?~~
No
I've used regular expression to solve the "unitname" problem on Quarkus properties, but the project preference seems to be glob expressions.
=> Find profiles and properties and change property keys

src/test/java/org/openrewrite/quarkus/AddQuarkusPropertyTest.java, src/test/java/org/openrewrite/quarkus/ChangeQuarkusPropertyKeyTest.java, src/test/java/org/openrewrite/quarkus/ChangeQuarkusPropertyValueTest.java, src/test/java/org/openrewrite/quarkus/DeleteQuarkusPropertyTest.java
Update tests to expect the new property insertion order introduced in  https://github.com/openrewrite/rewrite/commits/main/rewrite-properties/src/main/java/org/openrewrite/properties
The exact insertion point depends on properties already present, which is tested in openrewrite/rewrite extensively and should work better in practice versus what the tests indicate in the minimal examples here.
Fix tests to get build going again.
=> Expect new property prefix insertion order in tests

src/main/java/org/openrewrite/quarkus/AddQuarkusProperty.java, src/main/java/org/openrewrite/quarkus/ChangeQuarkusPropertyKey.java, src/main/java/org/openrewrite/quarkus/ChangeQuarkusPropertyValue.java, src/main/java/org/openrewrite/quarkus/DeleteQuarkusProperty.java, src/main/java/org/openrewrite/quarkus/search/FindQuarkusProperties.java, src/test/java/org/openrewrite/quarkus/AddQuarkusPropertyTest.java, src/test/java/org/openrewrite/quarkus/ChangeQuarkusPropertyKeyTest.java, src/test/java/org/openrewrite/quarkus/ChangeQuarkusPropertyValueTest.java, src/test/java/org/openrewrite/quarkus/DeleteQuarkusPropertyTest.java, src/test/java/org/openrewrite/quarkus/search/FindQuarkusPropertiesTest.java
- Update FindQuarkusProperties to use the custom pathExpression to support dependent Add/Change?delete property recipes
- Fixes https://github.com/openrewrite/rewrite-quarkus/issues/92
@timtebeek 
Post fix the recipe should be able to recognize property files other than default application.properties
=> Quarkus Add/Change/Delete property recipe to use the custom pathExpression

build.gradle.kts, src/main/resources/META-INF/rewrite/javaee7-to-quarkus.yml, src/test/java/org/openrewrite/quarkus/migrate/javaee/JavaEEtoQuarkus2MavenDependenciesMigrationTest.java
- https://github.com/quarkusio/quarkus-updates/pull/242
=> Drop `rewrite-migrate-java` dependency to limit ourselves to ASL

src/main/java/org/openrewrite/quarkus/AddQuarkusProperty.java, src/main/java/org/openrewrite/quarkus/ChangeQuarkusPropertyKeyVisitor.java, src/main/java/org/openrewrite/quarkus/ChangeQuarkusPropertyValueVisitor.java, src/main/java/org/openrewrite/quarkus/DeleteQuarkusPropertyVisitor.java
**What**:
Adding extra parameter for `AddProperty` recipe after it got added in https://github.com/openrewrite/rewrite/pull/6052
**Why**:
Fix broken CI.
=> Dealing with extra parameter for AddProperty
